### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by Evavic44** [CommunityPro/Practice-Contribution#4]
Add guidelines for anyone looking to contribute to this project.

Things to mention
- [x] The purpose of this project
- Things to look out for while trying to contribute like:
- [x] Prettier Indent
- [x] Mention of how we won't merge any PR that edits someone else's code unless required.

**Comment by Mannuel25** [comment]
Okay, I'm on it.

**Comment by Evavic44** [comment]
> Okay, I'm on it.

A simple example you can work with. https://github.com/prathimacode-hub/The-Tree-Musketeers/blob/main/CONTRIBUTING.md

Omit the `Steps to contribute`

**Comment by Mannuel25** [comment]
> > Okay, I'm on it.
> 
> A simple example you can work with. https://github.com/prathimacode-hub/The-Tree-Musketeers/blob/main/CONTRIBUTING.md
> 
> Omit the `Steps to contribute`

Oh, I actually didnt know you left an example to work with 😅. I had to just think of something to put down. 

Is the contribution guidelines okay? Or I should make changes in respect to the example you provided?

**Comment by Mannuel25** [comment]
> Add guidelines for anyone looking to contribute to this project.
> 
> Things to mention
> 
> * [x] The purpose of this project
> * [x] Things to look out for while trying to contribute like:
> * [x]  Prettier Indent
> * [x]  Mention of how we won't merge any PR that edits someone else's code unless required.
