### ISSUE TITLE
[BUG] <Double profile in contributors list>

### ISSUE THREAD

**Issue by Evavic44** [CommunityPro/Practice-Contribution#46]
### Description of the bug

In the contributors list, a users profile was added twice, request to remove one. 

### Project stack or language (e.g. front-end)

Frontend

### Working Environment (e.g. operating system, browser, device)

Windows, Laptop

### Please add screenshots (if applicable)

![double-profile](https://user-images.githubusercontent.com/62628408/148194627-84a7bfd7-8e22-432c-beff-8b7f44676a9d.png)

**Comment by Evavic44** [comment]
Nice work @Jummate 🙌🏾

**Comment by Jummate** [comment]
@Evavic44 
Thanks boss.
