### ISSUE TITLE
[BUG] <Fix blurry image>

### ISSUE THREAD

**Issue by Evavic44** [CommunityPro/Practice-Contribution#55]
### Description of the bug

On `<!-- Start of column-17 -->` fix the blurry image of Mustapha Olawale's profile

### Project stack or language (e.g. front-end)

Frontend

### Working Environment (e.g. operating system, browser, device)

Firefox, Windows 

### Please add screenshots (if applicable)

![blur](https://user-images.githubusercontent.com/62628408/148331104-69392d9e-a535-42e5-8deb-c6890c9042d6.png)

**Comment by keleris32** [comment]
Good day Eke, how do contribute to solve this issue? Do I create a new branch with the fix and push to the repo, or do I just make changes on main branch and push to the repo?

**Comment by winniffy** [comment]
hello @Evavic44, i tried to fix the bug. kindly check it out.

**Comment by Evavic44** [comment]
> Good day Eke, how do contribute to solve this issue? Do I create a new branch with the fix and push to the repo, or do I just make changes on main branch and push to the repo?

Sorry @keleris32 but this issue has already been fixed, you can check out other issues. Here's one: https://github.com/CommunityPro/support/issues/55 keep looking out for more issues. Thanks. 🙏🏽

**Comment by Evavic44** [comment]
> hello @Evavic44, i tried to fix the bug. kindly check it out.

Good Job Winniffy. 🙌🏾😎 Thanks for your contribution. Keep looking out for more issues.
